# Site settings
title: LAN-TI Saint-Félicien 2e Édition
email: info@lantistfe.info
description: > # this means to ignore newlines until "baseurl:"
  Site du LAN des techniques de l'informatique du cégep de St-Félicien
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lantistfe.info" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
facebook_event_num: 1500346320263542
facebook_event_name: LAN-TI Saint-Félicien 2e Édition

# Build settings
markdown: kramdown
